<?php
// Oracle écrit par Gemma (gemma-4-31b-it) pour PR #30342, validé pre/post automatiquement
require 'config/config.inc.php';

$context = Context::getContext();
$context->shop = new Shop(1);
$context->language = new Language(1);

// Ensure a supplier exists for the test
$supplier = new Supplier(1);
if (!Validate::isLoadedObject($supplier)) {
    $supplier = new Supplier();
    $supplier->name = 'Test Supplier';
    $supplier->active = 1;
    $supplier->add();
}

$id_supplier = (int)$supplier->id;

// Parameters that would be passed by the {url entity='supplier' id=1} helper in Smarty
$params = [
    'entity' => 'supplier',
    'id' => $id_supplier,
];

// Call the method targeted by the fix
$url_smarty = Link::getUrlSmarty($params);

// Call the reference method that is known to generate the correct rewritten URL
// We pass 'true' for relativeProtocol to match the default behavior of getUrlSmarty
$url_reference = $context->link->getSupplierLink(
    $supplier,
    null,
    $context->language->id,
    $context->shop->id,
    true
);

echo "URL generated by getUrlSmarty: $url_smarty\n";
echo "URL generated by getSupplierLink: $url_reference\n";

// The test passes if the helper now returns the same rewritten URL as the reference method
if ($url_smarty === $url_reference) {
    exit(0);
} else {
    exit(1);
}
